=== Armandreano/ou-jabberpoint/jabberpoint.dtd
<!--
 Document Type Definition voor JabberPoint presentatties
 $Id$
 -->
<!ELEMENT showtitle (#PCDATA)>
<!ELEMENT presentation (showtitle,slide+)>
<!ELEMENT slide (item*)>
<!ATTLIST slide strategy CDATA #REQUIRED>
<!ELEMENT item (#PCDATA)>
<!ATTLIST item kind CDATA #REQUIRED>
<!ATTLIST item color CDATA #IMPLIED>
<!ATTLIST item fontname CDATA #IMPLIED>
<!ATTLIST item fontsize CDATA #IMPLIED>
<!ATTLIST item indent CDATA #REQUIRED>
<!ATTLIST item leading CDATA #REQUIRED>
<!ATTLIST item actions CDATA #IMPLIED>

=== Armandreano/ou-jabberpoint/showcase.xml
<?xml version="1.0"?>
<!DOCTYPE presentation SYSTEM "jabberpoint.dtd">
<presentation>
	<showtitle>Showcase</showtitle>
	<slide strategy="linear">
		<item kind="text"  color="red" fontname="Helvetica" fontsize="40" indent="0" leading="40" value="Showcase presentation"></item>
		<item kind="image" indent="0" leading="40" value="logo-woordmerk_ou.gif"></item>		
	</slide>
	<slide strategy="linear">
		<item kind="text" color="blue" indent="0" leading="40" value="Click here to play audio">
			<action name="audio" value="rickrollsoundeffect.wav"></action>
		</item>		
		<item kind="image" indent="0" leading="40" value="rick.png">
			<action name="link" value="https://www.youtube.com/watch?v=dQw4w9WgXcQ"></action>
		</item>
	</slide>
</presentation>
